"""baseline

Revision ID: 907155435c3a
Revises: 
Create Date: 2025-07-25 12:17:04.995930

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '907155435c3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
